version: '3'

services:

  mysql:
    build:
      context: ./database_service
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nodelogin
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost"]
      interval: 10s
      timeout: 5s
      retries: 3


  file_system:
    build:
      context: ./storage_service
      dockerfile: Dockerfile
    ports:
      - "5002:3002"
    volumes:
      - shared_volume:/storage_service/uploads

  authentication:
    build:
      context: ./login_service
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    depends_on:
      mysql:
        condition: service_healthy

  # video_streaming:
  #   build:
  #     context: ./video_service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5001:3001"
  #   depends_on:
  #     - authentication
  #     - file_system
  #     - mysql

  # upload_video:
  #   build:
  #     context: ./upload_service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5003:3003"
  #   depends_on:
  #     - authentication
  #     - file_system
  #     - mysql


volumes:
  mysql_data:
  shared_volume:
