version: '3'

services:
  upload_video:
    build:
      context: ./upload_video
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - authentication
      - mysql
      - file_system

  video_streaming:
    build:
      context: ./video_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - authentication
      - mysql
      - file_system

  authentication:
    build:
      context: ./login_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"

  file_system:
    build:
      context: ./storage_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"

  mysql:
    build:
      context: ./database_service
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nodelogin
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

