version: '3'

services:
  upload_video:
    build:
      context: ./upload_service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - authentication
      - mysql
      - file_system

  video_streaming:
    build:
      context: ./video_service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - authentication
      - mysql
      - file_system

  authentication:
    build:
      context: ./login_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  file_system:
    build:
      context: ./storage_service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  mysql:
    build:
      context: ./database_service
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nodelogin
      MYSQL_USER: sqluser
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

