apiVersion: apps/v1
kind: Deployment
metadata:
   name: login-deployment
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         app: login
   template:
      metadata:
         labels:
            app: login
      spec:
         containers:
            - name: login
              image: pumasy/login_service:latest
              ports:
                - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: login