apiVersion: apps/v1
kind: Deployment #Stateful set
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: pumasy/database_service:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: nodelogin
            - name: MYSQL_USER
              value: sqluser
            - name: MYSQL_PASSWORD
              value: password
